// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZIhFV2VffaU_5_RBk7EncXlQjwCaNQJs',
    appId: '1:749249311347:web:c45434582d33510954b006',
    messagingSenderId: '749249311347',
    projectId: 'bizzy-app-ab5b9',
    authDomain: 'bizzy-app-ab5b9.firebaseapp.com',
    storageBucket: 'bizzy-app-ab5b9.appspot.com',
    measurementId: 'G-N4VMBS30B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdiHcWNJvLyMb4zUOJ1K-fLkg-BiM7Aoo',
    appId: '1:749249311347:android:19971b9ce34653ff54b006',
    messagingSenderId: '749249311347',
    projectId: 'bizzy-app-ab5b9',
    storageBucket: 'bizzy-app-ab5b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfJcvVj40rDCKd4PbzOEslx87IPl_HmBM',
    appId: '1:749249311347:ios:cfe25904e9620d2b54b006',
    messagingSenderId: '749249311347',
    projectId: 'bizzy-app-ab5b9',
    storageBucket: 'bizzy-app-ab5b9.appspot.com',
    iosClientId: '749249311347-j0r6s1a5eo56mhlb2bltl3158hlg7g96.apps.googleusercontent.com',
    iosBundleId: 'com.saifo.bizzyupdated',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfJcvVj40rDCKd4PbzOEslx87IPl_HmBM',
    appId: '1:749249311347:ios:e48f041edd34f06054b006',
    messagingSenderId: '749249311347',
    projectId: 'bizzy-app-ab5b9',
    storageBucket: 'bizzy-app-ab5b9.appspot.com',
    iosClientId: '749249311347-1140cbhum6sn52l792138fjt7rll9bkm.apps.googleusercontent.com',
    iosBundleId: 'com.saifo.bizzyupdated.RunnerTests',
  );
}
